#continue statement in for loop

for i in range(4):# This line starts a for loop that will iterate over a sequence of numbers generated by the range function. The range(4) function generates a sequence of numbers from 0 to 3 (inclusive), so the loop will run four times with i taking on the values 0, 1, 2, and 3 in each iteration.
    print('printing') # This line prints the string 'printing' to the console. Each time the loop runs, it will output this string, so it will be printed four times in total, once for each value of i in the range.
    if i == 2:# This line checks if the current value of i is equal to 2. If this condition is true, it will execute the block of code inside the if statement.
        continue# This line will skip the rest of the code inside the loop for the current iteration when i is equal to 2. The continue statement is used to skip the current iteration and move on to the next iteration of the loop, so when i is 2, it will not execute any code below this line and will go back to the beginning of the loop for the next value of i.
    print(i) # This line prints the current value of i to the console. Each time